export { default as arrowIcon } from '#/assets/icons/general/arrow-icon.svg'
export { default as closeIcon } from '#/assets/icons/general/close-icon.svg'
export { default as logoIcon } from '#/assets/icons/general/logo.svg'
export { default as minusIcon } from '#/assets/icons/general/minus-icon.svg'
export { default as plusIcon } from '#/assets/icons/general/plus-icon.svg'
export { default as zoomIcon } from '#/assets/icons/general/zoom-icon.svg'

export { default as cvIcon } from '#/assets/icons/landing/cv-icon.svg'
export { default as emailIcon } from '#/assets/icons/landing/email-icon.svg'
export { default as githubIcon } from '#/assets/icons/landing/github-icon.svg'
export { default as linkedinIcon } from '#/assets/icons/landing/linkedin-icon.svg'

export { default as koloIcon } from '#/assets/icons/job-experience/kolo-icon.svg'

export { default as quizGameIcon } from '#/assets/icons/projects/quiz-game-icon.svg'
export { default as miniTranslatorIcon } from '#/assets/icons/projects/mini-translator-icon.svg'
export { default as jolcIcon } from '#/assets/icons/projects/jolc-icon.svg'

export { default as htmlIcon } from '#/assets/icons/skills/html-icon.svg'
export { default as cssIcon } from '#/assets/icons/skills/css-icon.svg'
export { default as javascriptIcon } from '#/assets/icons/skills/javascript-icon.svg'
export { default as typescriptIcon } from '#/assets/icons/skills/typescript-icon.svg'
export { default as reactjsIcon } from '#/assets/icons/skills/reactjs-icon.svg'
export { default as reduxIcon } from '#/assets/icons/skills/redux-icon.svg'
export { default as expressIcon } from '#/assets/icons/skills/express-icon.svg'
export { default as goIcon } from '#/assets/icons/skills/go-icon.svg'
export { default as pythonIcon } from '#/assets/icons/skills/python-icon.svg'
export { default as mongodbIcon } from '#/assets/icons/skills/mongodb-icon.svg'
export { default as mysqlIcon } from '#/assets/icons/skills/mysql-icon.svg'
export { default as oraclesqlIcon } from '#/assets/icons/skills/oraclesql-icon.svg'
export { default as javaIcon } from '#/assets/icons/skills/java-icon.svg'
export { default as awsIcon } from '#/assets/icons/skills/aws-icon.svg'
export { default as oraclecloudIcon } from '#/assets/icons/skills/oraclecloud-icon.svg'
