export const arrowIcon = 'general/arrow-icon.svg'
export const closeIcon = 'general/close-icon.svg'
export const cvIcon = 'landing/cv-icon.svg'
export const logoIcon = 'landing/logo-icon.svg'
export const minusIcon = 'general/minus-icon.svg'
export const plusIcon = 'general/plus-icon.svg'
export const zoomIcon = 'general/zoom-icon.svg'

export const emailIcon = 'landing/email-icon.svg'
export const githubIcon = 'landing/github-icon.svg'
export const linkedinIcon = 'landing/linkedin-icon.svg'

export const jolcIcon = 'projects/jolc-icon.svg'
export const koloEmpresasIcon = 'projects/kolo-empresas-icon.svg'
export const miniTranslatorIcon = 'projects/mini-translator-icon.svg'
export const quizGameIcon = 'projects/quiz-game-icon.svg'

export const awsIcon = 'skills/aws-icon.svg'
export const cssIcon = 'skills/css-icon.svg'
export const expressIcon = 'skills/express-icon.svg'
export const goIcon = 'skills/go-icon.svg'
export const htmlIcon = 'skills/html-icon.svg'
export const javaIcon = 'skills/java-icon.svg'
export const javascriptIcon = 'skills/javascript-icon.svg'
export const mongodbIcon = 'skills/mongodb-icon.svg'
export const mysqlIcon = 'skills/mysql-icon.svg'
export const oraclecloudIcon = 'skills/oraclecloud-icon.svg'
export const oraclesqlIcon = 'skills/oraclesql-icon.svg'
export const pythonIcon = 'skills/python-icon.svg'
export const reactjsIcon = 'skills/reactjs-icon.svg'
export const reduxIcon = 'skills/redux-icon.svg'
export const typescriptIcon = 'skills/typescript-icon.svg'
